#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("RSSParser.Resource", IsApplication=true)]

namespace RSSParser
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			// aapt resource value: 0x7f010008
			public const int bottomEdgeSwipeOffset = 2130771976;
			
			// aapt resource value: 0x7f01000a
			public const int clickToClose = 2130771978;
			
			// aapt resource value: 0x7f010004
			public const int drag_edge = 2130771972;
			
			// aapt resource value: 0x7f010000
			public const int layoutManager = 2130771968;
			
			// aapt resource value: 0x7f010005
			public const int leftEdgeSwipeOffset = 2130771973;
			
			// aapt resource value: 0x7f010002
			public const int reverseLayout = 2130771970;
			
			// aapt resource value: 0x7f010006
			public const int rightEdgeSwipeOffset = 2130771974;
			
			// aapt resource value: 0x7f010009
			public const int show_mode = 2130771977;
			
			// aapt resource value: 0x7f010001
			public const int spanCount = 2130771969;
			
			// aapt resource value: 0x7f010003
			public const int stackFromEnd = 2130771971;
			
			// aapt resource value: 0x7f010007
			public const int topEdgeSwipeOffset = 2130771975;
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Dimension
		{
			
			// aapt resource value: 0x7f040000
			public const int item_touch_helper_max_drag_scroll_per_frame = 2130968576;
			
			// aapt resource value: 0x7f040001
			public const int item_touch_helper_swipe_escape_max_velocity = 2130968577;
			
			// aapt resource value: 0x7f040002
			public const int item_touch_helper_swipe_escape_velocity = 2130968578;
			
			static Dimension()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Dimension()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int EmptyStar = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int Icon = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int Star = 2130837506;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f05000a
			public const int addToFavorite = 2131034122;
			
			// aapt resource value: 0x7f050011
			public const int articleDescription = 2131034129;
			
			// aapt resource value: 0x7f050010
			public const int articleFavorite = 2131034128;
			
			// aapt resource value: 0x7f05000e
			public const int articleImage = 2131034126;
			
			// aapt resource value: 0x7f050014
			public const int articleList = 2131034132;
			
			// aapt resource value: 0x7f05000f
			public const int articleTitle = 2131034127;
			
			// aapt resource value: 0x7f050007
			public const int articleView = 2131034119;
			
			// aapt resource value: 0x7f050001
			public const int bottom = 2131034113;
			
			// aapt resource value: 0x7f050012
			public const int favoriteBox = 2131034130;
			
			// aapt resource value: 0x7f050000
			public const int item_touch_helper_previous_elevation = 2131034112;
			
			// aapt resource value: 0x7f050005
			public const int lay_down = 2131034117;
			
			// aapt resource value: 0x7f050002
			public const int left = 2131034114;
			
			// aapt resource value: 0x7f050009
			public const int leftBottomWrapper = 2131034121;
			
			// aapt resource value: 0x7f05000d
			public const int mainView = 2131034125;
			
			// aapt resource value: 0x7f050006
			public const int pull_out = 2131034118;
			
			// aapt resource value: 0x7f050013
			public const int refreshLayout = 2131034131;
			
			// aapt resource value: 0x7f05000c
			public const int removeFromFavorite = 2131034124;
			
			// aapt resource value: 0x7f050003
			public const int right = 2131034115;
			
			// aapt resource value: 0x7f05000b
			public const int rightBottomWrapper = 2131034123;
			
			// aapt resource value: 0x7f050008
			public const int swipeLayout = 2131034120;
			
			// aapt resource value: 0x7f050004
			public const int top = 2131034116;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int Article = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int ArticleListItem = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int Main = 2130903042;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f060000
			public const int addToFavorite = 2131099648;
			
			// aapt resource value: 0x7f060001
			public const int removeFromFavorite = 2131099649;
			
			// aapt resource value: 0x7f060002
			public const int showFavorite = 2131099650;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Styleable
		{
			
			public static int[] RecyclerView = new int[] {
					16842948,
					2130771968,
					2130771969,
					2130771970,
					2130771971};
			
			// aapt resource value: 0
			public const int RecyclerView_android_orientation = 0;
			
			// aapt resource value: 1
			public const int RecyclerView_layoutManager = 1;
			
			// aapt resource value: 3
			public const int RecyclerView_reverseLayout = 3;
			
			// aapt resource value: 2
			public const int RecyclerView_spanCount = 2;
			
			// aapt resource value: 4
			public const int RecyclerView_stackFromEnd = 4;
			
			public static int[] SwipeLayout = new int[] {
					2130771972,
					2130771973,
					2130771974,
					2130771975,
					2130771976,
					2130771977,
					2130771978};
			
			// aapt resource value: 4
			public const int SwipeLayout_bottomEdgeSwipeOffset = 4;
			
			// aapt resource value: 6
			public const int SwipeLayout_clickToClose = 6;
			
			// aapt resource value: 0
			public const int SwipeLayout_drag_edge = 0;
			
			// aapt resource value: 1
			public const int SwipeLayout_leftEdgeSwipeOffset = 1;
			
			// aapt resource value: 2
			public const int SwipeLayout_rightEdgeSwipeOffset = 2;
			
			// aapt resource value: 5
			public const int SwipeLayout_show_mode = 5;
			
			// aapt resource value: 3
			public const int SwipeLayout_topEdgeSwipeOffset = 3;
			
			static Styleable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Styleable()
			{
			}
		}
	}
}
#pragma warning restore 1591
